### ISSUE TITLE
Ensure that `provider:"secret"` works as expected on the Provider resource

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-go-provider#251]
### What happened?

A customer found that provider fields marked as secret still showed up in the display. We need to attempt to replicate the issue and ensure that provider field secrets are handled correctly.

### Example

We can reproduce with the `credentials` example from this repo and the following program:

```yaml
name: dev-yaml
runtime: yaml

resources:
  provider:
    type: pulumi:providers:credentials
    properties:
      user: "hi"
      hash: Adler32
      password: "<do-not-show>"
plugins:
  providers:
    - name: credentials
      path: /Users/ianwahbe/go/src/github.com/pulumi/pulumi-go-provider/examples/credentials
```

### Output of `pulumi about`

```
CLI          
Version      3.126.1-dev.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME         VERSION
resource  credentials  unknown
language  yaml         unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in yaml

Current Stack: pulumi/dev-yaml/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::dev-yaml::pulumi:pulumi:Stack::dev-yaml-dev


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
